version: "3.3"
services:
  
  redis:
    image: redis
  rabbit:
    image: rabbitmq
  mongo:
    image: mongo

  api:
    image: sergioortegagomez/docker-node    
    volumes:
      - ./src:/opt/app
    ports: 
      - 3000:3000
    environment:
      - DEBUG=app*
    depends_on:
      - redis
      - rabbit
      - mongo